AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  odersapi

  Sample SAM Template for odersapi

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id

  CreateOrderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi
      Handler: com.dzhamal.aws.lambda.apis.CreateOrderLambda::createOrder
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
            
  ReadOrdersFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi
      Handler: com.dzhamal.aws.lambda.apis.ReadOrdersLambda::getOrders
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET